### ISSUE TITLE
Different behavior in the playground and runkit

### ISSUE THREAD

**Issue by RabbitJackTrade** [FontoXML/fontoxpath#255] opened 2020-06-24 14:45 UTC
I'm sort of new to this, so I may be missing something basic, but I have an xml snippet and an xpath expression, with the output working correctly [in the playground](https://xpath.playground.fontoxml.com/?xml=%3Cconversion%3E%0A%09%3CconvTable+date%3D%2220040212%22+currency%3D%22cdn%22%3E%0A%09%09%3Crate+currency%3D%22eur%22%3E0.59376%3C%2Frate%3E%0A%09%09%3Crate+currency%3D%22mxn%22%3E8.37597%3C%2Frate%3E%0A%09%09%3Crate+currency%3D%22jpy%22%3E80.23451%3C%2Frate%3E%0A%09%09%3Crate+currency%3D%22usd%22%3E0.76138%3C%2Frate%3E%0A%09%3C%2FconvTable%3E%0A%3C%2Fconversion%3E&xpath=%2F%2F*%2F%40currency&mode=0&variables=%7B%7D&context=) but when  [ran in runkit](https://runkit.com/thejack/fontoxpath-vs-xpath) gives the wrong answer while xpath gives the correct answer.

Any insight is appreciated.

**Comment by bwrrp** [comment] 2020-06-25 09:52
This appears to be caused by a bug in xmldom (jindw/xmldom#108). The namespaceURI for the attribute nodes is undefined rather than null (as required by the spec). We generally recommend using slimdom-sax-parser to parse XML, as that implementation more closely follows the spec. Alternatively, for code running in the browser (such as the playground) you could use the native DOMParser.

**Comment by DrRataplan** [comment] 2020-06-25 13:28
Duplicate of #21 by the way. XMLDom is not spec-compliant and is abandoned. There has been a PR open with the fix for this exact issue for almost two years now. We use FontoXPath and XML in general extensively in our main product (the Fonto editor) and we exclusively use [slimdom](https://github.com/bwrrp/slimdom.js) and the built-in browser DOM with good results. I would recommend anyone who really wants to use XML in the browser to do the same. As @bwrrp said, [https://github.com/wvbe/slimdom-sax-parser](slimdom-sax-parser) is a parser that we recommend to use with slimdom, since slimdom does not contain its own parser.

**Closed by DrRataplan** 2020-06-25 13:28 UTC

**Comment by RabbitJackTrade** [comment] 2020-06-25 21:20
Thanks you both for the insight. As they say - learn something new every day...
