### ISSUE TITLE
Type problem with 3.18.0

### ISSUE THREAD

**Issue by egh** [FontoXML/fontoxpath#370] opened 2021-06-05 16:18 UTC
This could be a problem on my side. I don't understand how `npm` works. I think all my packages as as up-to-date as possible, but I now get this error when running `tsc` on my code:

```
✖ npm run build

> xjslt@0.0.1 build /home/egh/c/xjslt
> tsc && npm link

node_modules/fontoxpath/dist/fontoxpath.d.ts:433:102 - error TS2307: Cannot find module '../parsing/convertXDMReturnValue' or its corresponding type declarations.

433 export declare const executeJavaScriptCompiledXPath: <TNode extends Node, TReturnType extends import("../parsing/convertXDMReturnValue").ReturnType>(compiledJavaScriptFunction: any, contextItem?: any, domFacade?: IDomFacade) => IReturnTypes<TNode>[TReturnType];
                                                                                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by DrRataplan** [comment] 2021-06-05 20:47
Hey Erik,

Thank you so much for bringing this to our attention! I believe this is
something caused by the 3.18 release, but I wonder how it relates... That
dynamic import there makes absolutely no sense at all and I am curious to
see how we made our typescript compiler do that.

I'll look into this asap!

Regards,

Martin

**Comment by egh** [comment] 2021-06-05 20:59
Thanks, Martin! The code is here github.com/egh/xjslt if that helps. I wish I knew enough about typescript to have a clue here :grinning:

**Comment by DrRataplan** [comment] 2021-06-07 07:58
I found it, kind-of. At some point, the build process for declarations (https://github.com/FontoXML/fontoxpath/blob/master/build.js#L62) decides to output the following for executeJavaScriptCompiledXPath.d.ts:
```
declare const executeJavaScriptCompiledXPath: <TNode extends Node, TReturnType extends import("../parsing/convertXDMReturnValue").ReturnType>(compiledJavaScriptFunction: any, contextItem?: any, domFacade?: IDomFacade) => IReturnTypes<TNode>[TReturnType];
export default executeJavaScriptCompiledXPath;
```

That is a dynamic import, which is not supported by the api-extractor tooling we use. However, that dynamic import is placed in by the TypeScript compiler because the original file imports it normally.

I'll have to dive in this more carefully because we are doing exactly the same in `evaluateXPath.ts`. Only difference is that we import more things from that module.

This is easily reproducable by running `npm run build` and checking the `dist/fontoxpath.d.ts` file by hand. The error is already present in `build/jscodegen/executeJavaScriptCompiledXPath.ts`.

**Comment by DrRataplan** [comment] 2021-06-07 08:32
I just pushed a fix. I will test it later, especially whether the generic return type infrastructure is still working. If you want to help, you should be able to check out the `simplification` branch and `npm link` it into your repo.

Some tests are still failing, but they seem to fail because of some typing that is set up a bit nasty in tests. I will find some time tomorrow for that.

@jarivm I do not know if you are able to help on this, but that would be very welcome!

**Comment by egh** [comment] 2021-06-07 16:12
Seems to work for me locally. At least, it builds and my tests pass.

**Comment by jarivm** [comment] 2021-06-08 07:07
Could reproduce it. The `simplification` branch solves it for me too. Strange that TS did not catch this error earlier.

**Comment by DrRataplan** [comment] 2021-06-11 08:33
Just merged that PR, I will make a release so that you can use it without a link

**Closed** 2021-06-11 08:33 UTC

**Comment by egh** [comment] 2021-06-11 14:40
Thank you! The new release works perfectly.
