### ISSUE TITLE
Attribute nodes are not sorted correctly in document order

### ISSUE THREAD

**Issue by ThomasGravekamp** [FontoXML/fontoxpath#190] opened 2019-12-19 10:37 UTC
This issue can be reproduced using the [Playground](https://xpath.playground.fontoxml.com/?mode=0&variables=%7B%7D&xml=%3Cxml+id%3D%22doc-1%22%3E%0A++%3Cparagraph+id%3D%22p-1%22%3EParagraph+content.%3C%2Fparagraph%3E%0A%3C%2Fxml%3E&xpath=%28%3A+Select+all+nodes+and+attributes+%3A%29%0A%2F%2Fnode%28%29+%7C+%2F%2Fattribute%28%29&context=).

In this example, all nodes and all attributes are selected. The resulting sequences are then joined using a [union expression](https://www.w3.org/TR/xpath-31/#combining_seq). The spec states that the resulting sequence of this expression should be returned in document order.

The [definition of document order](https://www.w3.org/TR/xpath-31/#id-document-order) states that:

* "3. Namespace nodes immediately follow the element node with which they are associated."
* "4. Attribute nodes immediately follow the namespace nodes of the element node with which they are associated."

As can be seen in the playground, the returned sequence contains the nodes and _then_ all attributes:

1. xml element
2. paragraph element
3. text node
4. xml id attribute
5. paragraph id attribute

The expected result would have been this:

1. xml element
2. xml id attribute
3. paragraph element
4. paragraph id attribute
5. text node

**Comment by DrRataplan** [comment] 2019-12-19 14:50
correct, this may go wrong in the shortcuts we use for the Path expression, we prevent sorting in some cases when we thing a sorting step is not needed.

**Comment by DrRataplan** [comment] 2020-01-06 16:35
After a bit of searching, the bug is in the playground! it seems that the domFacade over there is not implemented corretly. A `domFacade` must return the `ownerElement` for an attribute node when `getParentNode` method is used.

Not a bug in fontoXPath, closing it. I'll make a new bug for the playground on the correct board.

**Closed by DrRataplan** 2020-01-06 16:35 UTC
